In [11]:
from src.runner import preprocess
preprocess()

Processing Center for Advanced Life Cycle Engineering cells: 100%|██████████| 7/7 [00:01<00:00,  4.08it/s]


0 processed, 7 skipped



Processing Hawaii Natural Energy Institute cells: 100%|██████████| 15/15 [00:03<00:00,  3.78it/s]


0 processed, 15 skipped



Processing Oxford cells: 100%|██████████| 8/8 [00:01<00:00,  5.27it/s]


8 processed, 0 skipped



Processing Oak Ridge National Lab cells: 100%|██████████| 253/253 [01:19<00:00,  3.19it/s]


230 processed, 23 skipped



Processing Sandia National Lab cells: 100%|██████████| 32/32 [00:04<00:00,  7.56it/s]


74 processed, 12 skipped



Processing Underwriters Lab - Purdue University cells: 100%|██████████| 22/22 [00:02<00:00,  7.86it/s]

21 processed, 1 skipped



In [37]:
from src.data import BatteryData
oxford_data = BatteryData.load('data/preprocessed/OX_1-1_pouch_LCO_40C_0-100_2-1.84C_a_timeseries.pkl')
# oxford_data.print_description()
ts = next(t for t in oxford_data.timeseries_data)
ts.display()

,time_in_s,temperature_in_C
0,0.000000e+00,40.026
1,9.990000e-01,40.051
2,1.999000e+00,39.988
3,2.999000e+00,39.976
4,3.999000e+00,39.964
...,...,...
460376,5.518128e+07,40.737
460377,5.518128e+07,40.750
460378,5.518128e+07,40.688
460379,5.518128e+07,40.725


In [36]:
from src.data import BatteryData
filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
cell = BatteryData.load(filename)
# cell.print_description()

ts = next(t for t in cell.timeseries_data)
ts.display()


Timeseries Data description: tc1, positive-terminal


,time_in_s,temperature_in_C
0,0.000000,22.364101
1,0.099609,22.358707
2,0.199219,22.365358
3,0.298828,22.381090
4,0.398438,22.315783
...,...,...
38712,3856.078125,29.106949
38713,3856.177734,29.090010
38714,3856.277344,29.108253
38715,3856.376953,29.104151


In [2]:
from src.data.train_test_split import *
from src.utils.config import YamlHandler
from sklearn.model_selection import train_test_split

configs=YamlHandler('configs/dummy.yaml').read_yaml()

x1, x2, y1, y2 = load_train_test_split(configs=configs)
print(len(x1), len(x2), len(y1), len(y2))


584 146 584 146


In [6]:
from src.utils.config import YamlHandler
from src.data.battery_data import BatteryData

handler = YamlHandler('configs/dummy.yaml')
config = handler.read_yaml()


config = config.get('train_test_split', config)
config

def testconfig(configs, data=None):
    configs = configs.get('train_test_split', configs) # open configs if needed

    for filter in configs.battery_filters:
        print(filter, type(filter))

        filterattr = getattr(configs.battery_filters, filter)
        dataattr = getattr(data, filter, None)
        print(filterattr)
        print(dataattr)

        print(dataattr in filterattr)
        print()

    print(any(getattr(data, filter, None) in getattr(configs.battery_filters, filter) for filter in configs.battery_filters))


filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
cell = BatteryData.load(filename)

testconfig(config, cell)
cell.anode_material

anode_material <class 'str'>
['graphitee']
graphite
False

cathode_material <class 'str'>
['NMC']
LFP
False

False


'graphite'

In [8]:
from src.utils.config import import_config
from pathlib import Path

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
# config = config['train_test_split']
x1, x2, y1, y2 = load_train_test_split(configs=config)
# print(len(x1), len(x2), len(y1), len(y2))
x2

Missing expected config fields: ['t']


[       time_in_s  temperature_in_C
 0            0.0               NaN
 1            0.2               NaN
 2            0.4               NaN
 3            0.6               NaN
 4            0.8               NaN
 ...          ...               ...
 13655        NaN               NaN
 13656        NaN               NaN
 13657        NaN               NaN
 13658        NaN               NaN
 13659        NaN               NaN
 
 [13660 rows x 2 columns],
       time_in_s  temperature_in_C
 0          1.06              16.0
 1          2.06              16.0
 2          3.06              16.0
 3          4.06              16.0
 4          5.06              16.0
 ...         ...               ...
 3969    3970.06              30.3
 3970    3971.06              30.3
 3971    3972.06              30.4
 3972    3973.06              30.4
 3973    3974.06              30.4
 
 [3974 rows x 2 columns],
       time_in_s  temperature_in_C
 0         0.000          23.03782
 1         0.266     

In [12]:
y2

AttributeError: 'list' object has no attribute 'float'

In [5]:
from src.utils import import_config
from pathlib import Path
from src.data.train_test_split import load_train_test_split

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
# config = config['train_test_split']
x1, x2, y1, y2 = load_train_test_split(configs=config)
# print(len(x1), len(x2), len(y1), len(y2))
x2[0]

Missing expected config fields: ['t']


Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 957.29it/s]


array([[1.06000e+00, 2.62000e+01],
       [2.06000e+00, 2.63000e+01],
       [3.06000e+00, 2.62000e+01],
       ...,
       [2.84706e+03, 3.22000e+01],
       [2.84806e+03, 3.22000e+01],
       [2.84906e+03, 3.21000e+01]])

In [8]:
from src.utils import import_config, YamlHandler
from src.data.train_test_split import *

configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
extract_attributes_from_dir(configs=configs['train_test_split'])

Missing expected config fields: ['t']


Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3043.58it/s]


([array([[6.00000000e-02, 2.47720000e+01],
         [7.20400000e+00, 2.47720000e+01],
         [7.20400000e+00, 2.47720000e+01],
         ...,
         [1.23596109e+07, 3.02020000e+01],
         [1.23597309e+07, 3.04090000e+01],
         [1.23598509e+07, 3.03480000e+01]]),
  array([[1.00110000e+01, 2.61550000e+01],
         [2.00140000e+01, 2.61550000e+01],
         [3.00230000e+01, 2.62310000e+01],
         ...,
         [9.49708384e+06, 2.89790000e+01],
         [9.49708487e+06, 2.90400000e+01],
         [9.49708518e+06, 2.90400000e+01]]),
  array([[1.06000e+00, 2.13000e+01],
         [2.06000e+00, 2.13000e+01],
         [3.06000e+00, 2.13000e+01],
         ...,
         [4.02706e+03, 1.98000e+01],
         [4.02806e+03, 1.98000e+01],
         [4.02906e+03, 1.98000e+01]]),
  array([[1.06000e+00, 2.13000e+01],
         [2.06000e+00, 2.13000e+01],
         [3.06000e+00, 2.13000e+01],
         ...,
         [4.02706e+03, 2.15000e+01],
         [4.02806e+03, 2.15000e+01],
         [4.029

In [1]:
from src.data import DataBundle, Dataset
from src.utils.config import import_config
from src.data.train_test_split import *
import numpy as np
import torch

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
x1, x2, y1, y2 = load_train_test_split(configs=config, dtype='numpy')
bundle = DataBundle(x1, y1, x2, y2)
# ds1 = Dataset(x1, y1)
# ds2 = Dataset(x2, y2)
# # len(ds1), len(ds2)
# ds1.feature

# npx1 = np.array(x1, dtype=object)

# torchx1 = torch.nested.nested_tensor([torch.from_numpy(arr).float() for arr in x1])
# torchy1 = torch.tensor(y1).float()
# torchy1
bundle

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Missing expected config fields: ['t']


Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3605.45it/s]


In [3]:
from src.data import DataBundle, Dataset
from src.utils.config import import_config
from src.data.train_test_split import *

config = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
x1, x2, y1, y2 = load_train_test_split(configs=config, dtype='tensor')
bundle = DataBundle(torch.nested.nested_tensor(x1), y1, torch.nested.nested_tensor(x2), y2)

# from src.models import NNModel, MLPRULPredictor, LSTMRULPredictor, DummyRULPredictor

# nn_model = DummyRULPredictor()

# nn_model.fit(bundle)

Missing expected config fields: ['t']


Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3657.45it/s]


RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue.

In [16]:
from src.data import BatteryData
from src.data.train_test_split import *


from src.utils.config import import_config
from src.data.experiment_dataset import *

configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
dirname = 'data/preprocessed/'
filename = 'data/preprocessed/SNL_LFP_Graphite_10Ah_100SOC_b.pkl'
battery_data = BatteryData.load(filename)

datalist = extract_attributes_from_dir(dirname, configs=configs['train_test_split'])
datalist, len(datalist)

Missing expected config fields: ['t']


Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 2968.47it/s]


([(tensor([[6.0000e-02, 2.4772e+01],
           [7.2040e+00, 2.4772e+01],
           [7.2040e+00, 2.4772e+01],
           ...,
           [1.2360e+07, 3.0202e+01],
           [1.2360e+07, 3.0409e+01],
           [1.2360e+07, 3.0348e+01]]),
   tensor(1.)),
  (tensor([[1.0011e+01, 2.6155e+01],
           [2.0014e+01, 2.6155e+01],
           [3.0023e+01, 2.6231e+01],
           ...,
           [9.4971e+06, 2.8979e+01],
           [9.4971e+06, 2.9040e+01],
           [9.4971e+06, 2.9040e+01]]),
   tensor(1.)),
  (tensor([[1.0600e+00, 2.1300e+01],
           [2.0600e+00, 2.1300e+01],
           [3.0600e+00, 2.1300e+01],
           ...,
           [4.0271e+03, 1.9800e+01],
           [4.0281e+03, 1.9800e+01],
           [4.0291e+03, 1.9800e+01]]),
   tensor(0.)),
  (tensor([[1.0600e+00, 2.1300e+01],
           [2.0600e+00, 2.1300e+01],
           [3.0600e+00, 2.1300e+01],
           ...,
           [4.0271e+03, 2.1500e+01],
           [4.0281e+03, 2.1500e+01],
           [4.0291e+03, 2.1400e

In [47]:
from src.data.experiment_dataset import * 
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

class ExperimentDataset(torch.utils.data.Dataset):
    def __init__(self, data = []):
        self.data = data 

    def __getitem__(self, idx):
        return self.data[idx]
    
    def __len__(self):
        return len(self.data)
    
    def append_data(self, data):
        self.data += data 
    
    def add(self, feature, label):
        self.data.append((feature, label))

def collate_fn(batch):
    sequences, labels = zip(*batch)
    padded = pad_sequence(sequences, batch_first=True)  # shape: (B, T_max, D)
    lengths = torch.tensor([seq.size(0) for seq in sequences])
    labels = torch.stack(labels)  # shape: (B,)
    return padded, labels, lengths

train_data, test_data = load_train_test_split()

train_dataset = ExperimentDataset(train_data)
test_dataset = ExperimentDataset(test_data)

train_loader = DataLoader(train_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
# for padded_batch, label_batch, lengths in test_loader:
#     print(f"Padded: {padded_batch.shape}, Labels: {label_batch}, Lengths: {lengths}")
#     break  # one batch only

batch = next(iter(test_loader))
print(batch[0].size(), batch[1].size(), batch[2].size())
batch[0].size(-1)
# print(f"Feature batch shape: {test_features.size()}")
# print(f"Labels batch shape: {test_labels.size()}")

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 1329.15it/s]

torch.Size([40, 596958, 2]) torch.Size([40]) torch.Size([40])


2

In [48]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        super(LSTMModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.layer_dim = layer_dim
        self.lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, h0=None, c0=None):
        if h0 is None or c0 is None:
            h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
            c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).to(x.device)
        
        out, (hn, cn) = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out, hn, cn
    

model = LSTMModel(input_dim=2, hidden_dim=100, layer_dim=1, output_dim=1)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

def trainLSTM(model, dataloader, criterion, num_epochs=3):
    device = 'cpu'

    model.to(device)
    model.train()

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    h0, c0 = None, None

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for batch in dataloader:
            outputs, h0, c0 = model(batch[0], h0, c0)

            loss = criterion(outputs, batch[1])
            loss.backward()
            optimizer.step()

            h0 = h0.detach()
            c0 = c0.detach()

        avg_loss = epoch_loss / len(dataloader)
        print(f"Epoch {epoch}/{num_epochs}, Loss: {avg_loss:.4f}")

    
trainLSTM(model, train_loader, criterion)

/Users/Hanita/Library/Python/3.12/lib/python/site-packages/torch/nn/modules/loss.py:538: UserWarning: Using a target size (torch.Size([40])) that is different to the input size (torch.Size([40, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [5]:
from src.models import NNModel, MLPRULPredictor, MultiLayerPerceptronModule, LSTMRULPredictor
from src.data import DataBundle

# Licensed under the MIT License.
# Copyright (c) Microsoft Corporation.
from sklearn.metrics import roc_auc_score
import abc
import torch
import random
import numpy as np
import torch.nn as nn
import torch.optim as optim

from tqdm import tqdm
from torch.utils.data.dataloader import DataLoader

from src.data import DataBundle

from .base import BaseModel


def seed_worker(worker_id):
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)


class NNModel(BaseModel, nn.Module, abc.ABC):
    def __init__(self,
                 batch_size: int = 32,
                 epochs: int = 10000,
                 workspace: str = None,
                 evaluate_freq: int = 500,
                 checkpoint_freq: int = 1000,
                 train_batch_size: int = None,
                 test_batch_size: int = None,
                 lr: float = 1e-3):
        nn.Module.__init__(self)
        BaseModel.__init__(self, workspace)
        self.train_epochs = epochs
        self.evaluate_freq = evaluate_freq
        if checkpoint_freq is None or checkpoint_freq == 'None':
            self.checkpoint_freq = None
        else:
            self.checkpoint_freq = min(checkpoint_freq, self.train_epochs)
        self.train_batch_size = train_batch_size or batch_size
        self.test_batch_size = test_batch_size or batch_size
        self.lr = lr

    def fit(self,
            trainloader,
            testloader,
            traindataset,
            testdataset,
            timestamp: str = None,
            seed: int = 0):
        self.train()
        # train_data = dataset.train_data
        # loader = DataLoader(
        #     train_data, self.train_batch_size,
        #     shuffle=True, worker_init_fn=seed_worker)
        loader = train_loader
        # TODO: support customization of optimizers
        optimizer = optim.Adam(self.parameters(), lr=self.lr)

        timestamp = timestamp or 'UnknownTime'

        latest = None
        for epoch in tqdm(range(self.train_epochs), desc='Traning'):
            self.train()
            for batch in loader:
                loss = self.forward(**batch, return_loss=True)
                if loss == torch.inf:
                    reset_parameters(self)
                    optimizer = optim.Adam(self.parameters(), lr=self.lr)
                else:
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

            if self.checkpoint_freq is not None and \
                    (epoch + 1) % self.checkpoint_freq == 0:
                filename = f'{timestamp}_seed_{seed}_epoch_{epoch+1}.ckpt'
                if self.workspace is not None:
                    self.dump_checkpoint(self.workspace / filename)
                    latest = self.workspace / filename

            if (epoch + 1) % self.evaluate_freq == 0:
                pred = self.predict(testdataset)
                score = roc_auc_score(testdataset, prediction)
                print(f'[{epoch+1}/{self.train_epochs}] RMSE {score:.2f}', flush=True)

        if self.workspace is not None:
            self.link_latest_checkpoint(latest)

    @torch.no_grad()
    def predict(self, dataset, data_type: str='test') -> torch.Tensor:
        self.eval()
        # test_data = dataset.test_data
        if data_type == 'test':
            test_data = dataset.test_data
        else:
            test_data = dataset.train_data
            
        loader = DataLoader(
            test_data, self.test_batch_size,
            shuffle=False, worker_init_fn=seed_worker)
        predictions = torch.cat([self.forward(**batch) for batch in loader])
        return predictions

    def to(self, device: str):
        return nn.Module.to(self, device)

    def dump_checkpoint(self, path: str):
        torch.save(self.state_dict(), path)

    def load_checkpoint(self, path: str):
        self.load_state_dict(torch.load(path))


def reset_parameters(model):
    @torch.no_grad()
    def weight_reset(m):
        reset_parameters = getattr(m, "reset_parameters", None)
        if callable(reset_parameters):
            m.reset_parameters()

    model.apply(weight_reset)


train_loader = DataLoader(train_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)
test_loader = DataLoader(test_dataset, batch_size=40, shuffle=True, collate_fn=collate_fn)

bundle = DataBundle(train_data=train_dataset, test_data=test_dataset)
nn_model = NNModel(
    batch_size=10,
    epochs=2
)

# nn_model.fit(bundle)
mlp = MLPRULPredictor(
    in_channels=2,
    channels=1,
    input_height=2,
    input_width=2,
    batch_size=10,
    epochs=2
)
mlp.fit(bundle)

Traning:   0%|          | 0/2 [00:00<?, ?it/s]


RuntimeError: stack expects each tensor to be equal size, but got [22410, 2] at entry 0 and [102167, 2] at entry 1

In [3]:
import os 
import torch
import numpy as np
from glob import glob 
from tqdm.auto import tqdm
from sklearn.model_selection import train_test_split

from src.config import config
from src.data import BatteryData, DataBundle

from src.data.train_test_split import * 
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):
    sequences, labels = zip(*batch)
    padded = pad_sequence(sequences, batch_first=True)  # shape: (B, T_max, D)
    lengths = torch.tensor([seq.size(0) for seq in sequences])
    labels = torch.stack(labels)  # shape: (B,)
    return padded, labels, lengths

# from src.utils.config import import_config

# configs = import_config('configs/dummy.yaml', ['train_test_split', 'name', 't'])
dirname = 'data/preprocessed/'

X_train, X_test, y_train, y_test = load_train_test_split(dirname, dtype=torch.tensor)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

bundle = DataBundle(X_train, y_train, X_test, y_test)
len(bundle.train_data)
len(bundle.test_data)

from src.models import DummyRULPredictor, LSTMRULPredictor, MLPRULPredictor

dummy = DummyRULPredictor()
dummy.fit(bundle)
dummy.predict(bundle)

Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 853.11it/s]


torch.Size([489, 2020541, 2]) torch.Size([123, 2020541, 2]) torch.Size([489]) torch.Size([123])


tensor([0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861, 0.1861,
        0.1861, 0.1861, 0.1861, 0.1861, 

In [9]:
from src.models.dummy import SklearnModel
from sklearn.linear_model import LinearRegression

class LinearRegressionRULPredictor(SklearnModel):
    def __init__(self, *args, workspace: str = None, **kwargs):
        SklearnModel.__init__(self, workspace)
        self.model = LinearRegression(*args, **kwargs)

linreg = LinearRegressionRULPredictor()
linreg.fit(bundle)
predictions = linreg.predict(bundle)
torch.round(predictions)

tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
mlp = MLPRULPredictor(
    in_channels=1,
    channels=1,
    input_height=596958,
    input_width=2, 
    epochs=2
)

mlp.fit(bundle)
mlp.predict(bundle)

Traning: 100%|██████████| 2/2 [00:05<00:00,  2.68s/it]


tensor([0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779,
        0.2779, 0.2779, 0.2779, 0.2779, 0.2779, 0.2779])

In [11]:
import random 
from pathlib import Path
from datetime import datetime

def set_seed(seed: int):
    print(f'Seed is set to {seed}.')
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

def timestamp(marker: bool = False):
    template = '%Y-%m-%d %H:%M:%S' if marker else '%Y%m%d%H%M%S'
    return datetime.now().strftime(template)


def train(model, databundle, criterion=None, num_epochs=3):
    set_seed(0)
    device = 'cpu'

    model = model.to(device)
    ts = timestamp()

    model.fit(databundle, timestamp=ts)
    return model, databundle

model = MLPRULPredictor(
    in_channels=1,
    channels=32,
    input_height=596958,
    input_width=2, 
    epochs=10,
    batch_size=128,
)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model, _ = train(model, bundle)
model.predict(bundle)


Seed is set to 0.


Training:   0%|          | 0/10 [00:00<?, ?it/s]

In [1]:
import torch
import torch.nn as nn
from src.utils.config import import_config
from src.data import DataBundle
from src.data.train_test_split import *
from src.models import *
configs = import_config('configs/mini.yaml', ['train_test_split'])
dirname = 'data/preprocessed/'

X_train, X_test, y_train, y_test = load_train_test_split(dirname, configs=configs, dtype=torch.tensor, test_size=0.5)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

mini_bundle = DataBundle(X_train, y_train, X_test, y_test)

class LSTMRULPredictor(NNModel):
    def __init__(self,
                input_size: int,
                hidden_size: int,
                 **kwargs):
        """
        Args:
            in_channels (int): 
        """
        NNModel.__init__(self, **kwargs)

        self.lstm = nn.LSTM(
            input_size, hidden_size, 2, batch_first=True)
        in_features = hidden_size
        self.fc = nn.Linear(in_features, 1)

    def forward(self,
                feature: torch.Tensor,
                label: torch.Tensor,
                return_loss: bool = False):
        if feature.ndim == 3:
            feature = feature.unsqueeze(1)
        B, _, H, _ = feature.size()
        x = feature.permute(0, 2, 1, 3).contiguous().view(B, H, -1)
        x, _ = self.lstm(x)
        x = x[:, -1].contiguous().view(B, -1)
        x = self.fc(x).view(-1)
        x = torch.sigmoid(x)

        if return_loss:
            # return torch.mean((x - label.view(-1)) ** 2)
            return nn.functional.binary_cross_entropy(x, label.view(-1))

        return x
    
my_lstm = LSTMRULPredictor(
    input_size=2,
    hidden_size=1,
    epochs=3,
)


/Users/Hanita/Library/Python/3.12/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Extracting attributes: 100%|██████████| 333/333 [00:00<00:00, 3008.76it/s]

torch.Size([56, 128943, 2]) torch.Size([56, 128943, 2]) torch.Size([56]) torch.Size([56])


In [2]:
my_lstm.fit(mini_bundle)

Training: 100%|██████████| 3/3 [01:52<00:00, 37.64s/it]


In [5]:
probs = my_lstm.predict(mini_bundle)
preds = (probs >= 0.5).int()
preds

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)

In [7]:
# configs = import_config('configs/mini.yaml', ['train_test_split'])
# dirname = 'data/preprocessed/'

# X_train, X_test, y_train, y_test = load_train_test_split(dirname, configs=configs, dtype=torch.tensor, test_size=0.5)
# print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

mini_bundle = DataBundle(X_train, y_train, X_test, y_test)
print(sum(mini_bundle.test_data.label))
mini_bundle.test_data.label

tensor(7.)


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [6]:
probs = my_lstm.predict(mini_bundle)
preds = (probs >= 0.5).int()
preds

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int32)